version: '3'
services:
  php-app:
    build: .
    ports:
      - "8000:80"  # Maps port 8000 on your host to port 80 in the container
    volumes:
      - .:/var/www/html  # Mounts the current directory in the container for live changes
